### ISSUE TITLE
Request more help, thanks

### ISSUE THREAD

**Issue by SaltFish001** [autoexpect/ffmpeg-rockchip-4.1.3#1]
Can give a list for dependents. Like packages on Debain/Ubuntu & other dependents need compile myself (like rkmpp..)

**Comment by autoexpect** [comment]
Compile with the configuration in build.sh, the library can be found here according to the SOC model, http://4.cybertty.com:1010/index.php?p=rk%2Fdebian

**Comment by palmip** [comment]
android 下支持 rk硬件解码和编码的编译代码能否分享下

**Comment by victorming666** [comment]
./configure --enable-librga报错：librga not found，但是rockchip-rga已经编译并安装在/usr/lib/librga.so了啊？

**Comment by autoexpect** [comment]
@victorming666 
linaro@linaro-alip:~$ ls -ahl /lib/aarch64-linux-gnu/librga.so*
lrwxrwxrwx 1 root root   11  1月  7  2022 /lib/aarch64-linux-gnu/librga.so -> librga.so.2
lrwxrwxrwx 1 root root   15  1月  7  2022 /lib/aarch64-linux-gnu/librga.so.2 -> librga.so.2.1.0
-rw-r--r-- 1 root root 112K  1月  7  2022 /lib/aarch64-linux-gnu/librga.so.2.1.0
